### ISSUE TITLE
python2 compatibility? - maximum recursion depth exceeded

### ISSUE THREAD

**Issue by jpsmith5** [pepkit/attmap#55]
Testing pipeline on python2 for backwards compatibility.

```
/home/jps3dp/src/peppro/pipelines/peppro.py --sample-name K562_small --genome hg38 --input /home/jps3dp/Downloads/proseq_analysis/K562_small.fq --single-or-paired single --prealignments rCRSd human_repeats --adapter fastp --dedup seqkit --trimmer seqtk -O /home/jps3dp/Downloads/proseq_analysis/fastp-seqkit-seqtk/preseq/05-30-19 -P 4
```
Results in:
```
Traceback (most recent call last):
  File "/home/jps3dp/src/peppro/pipelines/peppro.py", line 2285, in <module>
    sys.exit(main())
  File "/home/jps3dp/src/peppro/pipelines/peppro.py", line 564, in main
    ngstk = pypiper.NGSTk(pm=pm)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/ngstk.py", line 47, in __init__
    super(NGSTk, self).__init__()
  File "/home/jps3dp/.local/lib/python2.7/site-packages/attmap/ordattmap.py", line 22, in __init__
    super(OrdAttMap, self).__init__(entries or {})
  File "/usr/lib/python2.7/collections.py", line 64, in __init__
    self.__root
  File "/home/jps3dp/.local/lib/python2.7/site-packages/attmap/attmap_echo.py", line 32, in __getattr__
    return super(self.__class__, self).__getattr__(item, default, expand)
```
Then the ...line 32, return super... repeats for several hundred lines before failing with the following.
```
RuntimeError: maximum recursion depth exceeded
Pipeline status: running
Starting cleanup: 0 files; 0 conditional files for cleanup

### Pipeline failed at:  (05-30 13:34:03) elapsed: 0.0 _TIME_

Total time: 0:00:00
Failure reason: Pipeline failure. See details above.

Changed status from running to failed.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1744, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1638, in fail_pipeline
    raise e
Exception: Pipeline failure. See details above.
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1744, in _exit_handler
    self.fail_pipeline(Exception("Pipeline failure. See details above."))
  File "/home/jps3dp/.local/lib/python2.7/site-packages/pypiper/manager.py", line 1638, in fail_pipeline
    raise e
Exception: Pipeline failure. See details above.
```

Calling the pipeline with python3 immediately resolves.

**Comment by vreuter** [comment]
Yeah we probably need to bump up the lower bound on `attmap` version required by `pypiper`. Do you know what version of `attmap` was being used?

**Comment by jpsmith5** [comment]
That is result with both `0.12.3` and `0.13.dev`

**Comment by vreuter** [comment]
Good deal, thanks!
